language: go
go:
- 1.4
- tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go get .
script:
  - go test
  - $HOME/gopath/bin/goveralls -repotoken S7Knqu960fkLwIysF9Zi3YdpZeyoKv0TR